version: '3.9'
services:
  blogapp:
    container_name: blog-app
    build: ./                       #dockerfile path
    mem_limit: 512M
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
    ports:
      - "8181:8181"
#  review:
#    container_name: review
#    build: ./review-service
#    mem_limit: 512M
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - mysql
#    ports:
#      - "8082:8082"
#  product-composite:
#    container_name: composite
#    build: ./product-composite-service
#    mem_limit: 512M
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#  mongodb:
#    container_name: mongo
#    image: mongo:6.0.4
#    mem_limit: 512m
#    volumes:
#      - mongodata:/data/db
#    ports:
#      - "27017:27017"
#    command: mongod
#    healthcheck:
#      test: "mongostat -n 1"
#      interval: 5s
#      timeout: 2s
#      retries: 60
  mysql:
    container_name: mysql
    image: mysql:8.0.35
    mem_limit: 512m
#    volumes:
#      - sqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=moin
      - MYSQL_PASSWORD=moin
      - MYSQL_DATABASE=blog_db
#    healthcheck:
#      test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD  -e 'SHOW DATABASES'"
#      interval: 5s
#      timeout: 2s
#      retries: 60
#volumes:
#  sqldata:
#  mongodata: